[package]
name = "irori-int-demo"
description = "Virtual devices; the reference integration to copy."
version.workspace = true
edition.workspace = true
publish.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
irori-types.workspace = true
irori-integration.workspace = true

schemars.workspace = true
serde.workspace = true
tokio.workspace = true

[dev-dependencies]
serde_json.workspace = true

[[bin]]
name = "irori-ext-demo"
path = "src/main.rs"

[lints]
workspace = true
