[package]
name = "xtask"
description = "Repository automation: `cargo xtask <command>`."
version.workspace = true
edition.workspace = true
publish.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
irori-types.workspace = true
irori-rules.workspace = true
irori-protocol-mqtt.workspace = true
irori-protocol-zigbee.workspace = true
anyhow.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true

[lints]
workspace = true
