[package]
name = "xtask"
description = "Repository automation: `cargo xtask <command>`."
version.workspace = true
edition.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
irori-types.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
