[package]
name = "irori-int-mqtt"
description = "MQTT integration with Home Assistant MQTT Discovery."
version.workspace = true
edition.workspace = true
publish.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
irori-types.workspace = true
irori-integration.workspace = true

[lints]
workspace = true
