//! Builds every official extension and packs each one as a release asset.
//!
//! `cargo xtask package --target <triple> [--tool build|zigbuild] [--out <dir>]` builds each
//! extension in the catalog (`extensions/official.toml`) for `<triple>` and writes
//! `<out>/<bin>-<triple>.tar.gz`: a tarball of the package just as `crates/irori`'s
//! `stage_package` arranges it, the manifest, the icon, and the binary in `bin/`. The running
//! binary downloads these by name from a GitHub release (see `packages.rs`), so the naming and
//! the layout must stay in step with `download_github` and `install_archive`. The release
//! workflow runs this once per build target.

use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context as _, bail};
use serde::Deserialize;

/// One `[[extension]]` in `extensions/official.toml`, enough to build and stage the package.
#[derive(Debug, Deserialize)]
struct Official {
    source: String,
    #[serde(rename = "crate")]
    crate_name: String,
    bin: String,
}

#[derive(Debug, Deserialize)]
struct CatalogFile {
    extension: Vec<Official>,
}

pub fn run() -> anyhow::Result<()> {
    let mut target = None;
    let mut tool = "build".to_owned();
    let mut out = None;
    let mut args = std::env::args().skip(2);
    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--target" => target = Some(args.next().context("--target needs a value")?),
            "--tool" => tool = args.next().context("--tool needs a value")?,
            "--out" => out = Some(args.next().context("--out needs a value")?),
            other => bail!("unexpected argument to `package`: {other:?}"),
        }
    }
    let target = target.context("package needs --target <triple> (e.g. aarch64-apple-darwin)")?;
    if tool != "build" && tool != "zigbuild" {
        bail!("--tool must be `build` or `zigbuild`, not {tool:?}");
    }
    let root = workspace_root();
    let out = out
        .map(PathBuf::from)
        .unwrap_or_else(|| root.join("dist/packages"));
    let cargo = std::env::var("CARGO").unwrap_or_else(|_| "cargo".into());

    let text = fs::read_to_string(root.join("extensions/official.toml"))
        .context("extensions/official.toml is missing")?;
    let catalog: CatalogFile =
        toml::from_str(&text).context("extensions/official.toml is invalid")?;
    if catalog.extension.is_empty() {
        bail!("extensions/official.toml lists no extensions");
    }

    fs::create_dir_all(&out).with_context(|| format!("can't create {}", out.display()))?;
    for item in &catalog.extension {
        package(&cargo, &tool, &target, &root, &out, item)?;
    }
    println!(
        "packaged {} extensions into {}",
        catalog.extension.len(),
        out.display()
    );
    Ok(())
}

/// Builds one extension for `target` and writes its `<bin>-<triple>.tar.gz` asset.
fn package(
    cargo: &str,
    tool: &str,
    target: &str,
    root: &Path,
    out: &Path,
    item: &Official,
) -> anyhow::Result<()> {
    let source = root.join(&item.source);
    let manifest = source.join("irori-extension.toml");
    if !manifest.is_file() {
        bail!("this checkout has no extension at {}", source.display());
    }
    build(cargo, tool, target, root, &item.crate_name, &item.bin)?;

    let binary = root
        .join("target")
        .join(target)
        .join("release")
        .join(&item.bin);
    if !binary.is_file() {
        bail!("built binary missing at {}", binary.display());
    }

    let stage = out.join(format!("{}-{}", item.bin, target));
    let _ = fs::remove_dir_all(&stage);
    fs::create_dir_all(stage.join("bin"))
        .with_context(|| format!("can't create {}", stage.display()))?;
    fs::copy(&manifest, stage.join("irori-extension.toml"))?;
    let icon = source.join("icon.svg");
    if icon.is_file() {
        fs::copy(&icon, stage.join("icon.svg"))?;
    }
    // If the manifest declares a `config_schema` path (generated by `cargo xtask schemas`
    // alongside it), it must travel with the package too — otherwise a released install has a
    // manifest pointing at a schema file that was never shipped, and the settings form silently
    // never appears (`config_schema` reads as `None`, same failure as no schema at all).
    let schema = source.join("config.schema.json");
    if schema.is_file() {
        fs::copy(&schema, stage.join("config.schema.json"))?;
    }
    let exe = stage.join("bin").join(&item.bin);
    fs::copy(&binary, &exe)?;
    fs::set_permissions(&exe, PermissionsExt::from_mode(0o755))?;

    let archive = out.join(format!("{}-{}.tar.gz", item.bin, target));
    let status = Command::new("tar")
        .arg("-czf")
        .arg(archive.to_str().expect("the output path is UTF-8"))
        .arg("-C")
        .arg(stage.to_str().expect("the stage path is UTF-8"))
        .arg(".")
        .status()
        .context("couldn't run `tar`")?;
    if !status.success() {
        bail!("`tar` failed packaging {}", item.bin);
    }
    let _ = fs::remove_dir_all(&stage);
    let size = fs::metadata(&archive)
        .map(|meta| meta.len())
        .expect("the archive was just written");
    let icon = if icon.is_file() {
        "with icon"
    } else {
        "no icon"
    };
    println!("  {}: {size} bytes, {icon}", archive.display());
    Ok(())
}

/// Builds `<crate>` for `target` the way the release workflow builds the binary itself:
/// `zigbuild` on the Linux cells (static musl), plain `cargo build` elsewhere.
fn build(
    cargo: &str,
    tool: &str,
    target: &str,
    root: &Path,
    crate_name: &str,
    bin: &str,
) -> anyhow::Result<()> {
    let mut command = Command::new(cargo);
    match tool {
        "build" => {
            command.arg("build");
        }
        "zigbuild" => {
            command.arg("zigbuild");
        }
        other => bail!("--tool must be `build` or `zigbuild`, not {other:?}"),
    }
    command
        .args([
            "--locked",
            "--release",
            "--target",
            target,
            "-p",
            crate_name,
            "--bin",
            bin,
        ])
        .current_dir(root);
    let status = command
        .status()
        .with_context(|| format!("couldn't run `{cargo}`"))?;
    if !status.success() {
        bail!("building {crate_name} failed ({status})");
    }
    Ok(())
}

/// `xtask/` sits one level below the workspace root, wherever the repository is checked out.
fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask/ has a parent")
        .to_path_buf()
}
